# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import usuarios_pb2 as usuarios__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in usuarios_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UsuariosStub(object):
    """Definição do serviço Usuarios, que contém os métodos disponíveis
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ObterUsuarios = channel.unary_unary(
                '/usuarios.Usuarios/ObterUsuarios',
                request_serializer=usuarios__pb2.ObterUsuariosRequest.SerializeToString,
                response_deserializer=usuarios__pb2.ObterUsuariosResponse.FromString,
                _registered_method=True)
        self.CriarUsuario = channel.unary_unary(
                '/usuarios.Usuarios/CriarUsuario',
                request_serializer=usuarios__pb2.CriarUsuarioRequest.SerializeToString,
                response_deserializer=usuarios__pb2.CriarUsuarioResponse.FromString,
                _registered_method=True)


class UsuariosServicer(object):
    """Definição do serviço Usuarios, que contém os métodos disponíveis
    """

    def ObterUsuarios(self, request, context):
        """Obtém todos os usuários
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CriarUsuario(self, request, context):
        """Cria um novo usuário
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UsuariosServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ObterUsuarios': grpc.unary_unary_rpc_method_handler(
                    servicer.ObterUsuarios,
                    request_deserializer=usuarios__pb2.ObterUsuariosRequest.FromString,
                    response_serializer=usuarios__pb2.ObterUsuariosResponse.SerializeToString,
            ),
            'CriarUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.CriarUsuario,
                    request_deserializer=usuarios__pb2.CriarUsuarioRequest.FromString,
                    response_serializer=usuarios__pb2.CriarUsuarioResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'usuarios.Usuarios', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('usuarios.Usuarios', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Usuarios(object):
    """Definição do serviço Usuarios, que contém os métodos disponíveis
    """

    @staticmethod
    def ObterUsuarios(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usuarios.Usuarios/ObterUsuarios',
            usuarios__pb2.ObterUsuariosRequest.SerializeToString,
            usuarios__pb2.ObterUsuariosResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CriarUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/usuarios.Usuarios/CriarUsuario',
            usuarios__pb2.CriarUsuarioRequest.SerializeToString,
            usuarios__pb2.CriarUsuarioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
