apiVersion: v1
kind: Pod
metadata:
  name: servidor-python
  labels:
    name: servidor-python
spec:
  containers:
    - name: servidor-python
      image: mauricioandre/servidor-python:1.0

      ports:
        - containerPort: 8000

      resources:
        limits:
          memory: "100Mi"
          cpu: "100m"

      envFrom:
        - secretRef:
            name: servidor-python-secrets
