# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: usuarios.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'usuarios.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eusuarios.proto\x12\x08usuarios\"A\n\x07Usuario\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\r\n\x05senha\x18\x04 \x01(\t\"\x16\n\x14ObterUsuariosRequest\"<\n\x15ObterUsuariosResponse\x12#\n\x08usuarios\x18\x01 \x03(\x0b\x32\x11.usuarios.Usuario\"9\n\x13\x43riarUsuarioRequest\x12\"\n\x07usuario\x18\x01 \x01(\x0b\x32\x11.usuarios.Usuario\":\n\x14\x43riarUsuarioResponse\x12\"\n\x07usuario\x18\x01 \x01(\x0b\x32\x11.usuarios.Usuario2\xab\x01\n\x08Usuarios\x12P\n\rObterUsuarios\x12\x1e.usuarios.ObterUsuariosRequest\x1a\x1f.usuarios.ObterUsuariosResponse\x12M\n\x0c\x43riarUsuario\x12\x1d.usuarios.CriarUsuarioRequest\x1a\x1e.usuarios.CriarUsuarioResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'usuarios_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USUARIO']._serialized_start=28
  _globals['_USUARIO']._serialized_end=93
  _globals['_OBTERUSUARIOSREQUEST']._serialized_start=95
  _globals['_OBTERUSUARIOSREQUEST']._serialized_end=117
  _globals['_OBTERUSUARIOSRESPONSE']._serialized_start=119
  _globals['_OBTERUSUARIOSRESPONSE']._serialized_end=179
  _globals['_CRIARUSUARIOREQUEST']._serialized_start=181
  _globals['_CRIARUSUARIOREQUEST']._serialized_end=238
  _globals['_CRIARUSUARIORESPONSE']._serialized_start=240
  _globals['_CRIARUSUARIORESPONSE']._serialized_end=298
  _globals['_USUARIOS']._serialized_start=301
  _globals['_USUARIOS']._serialized_end=472
# @@protoc_insertion_point(module_scope)
